// GENERATED by `cargo xtask tokens` from design/tokens/tokens.json. Do not edit.
use crate::ui::{Hsla, rgb, rgba};

/// Semantic Bitacora colours (design system tokens).
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Palette {
    /// Barra superior y barra lateral izquierda
    pub side: Hsla,
    /// Fondo del editor / columna principal
    pub bg: Hsla,
    /// Panel derecho, calendario
    pub panel: Hsla,
    /// Tarjetas, popovers, campo del agente
    pub raised: Hsla,
    /// Hover / seleccionado neutro, chip LATER, burbuja de usuario
    pub hover: Hsla,
    /// Fondo del bloque en edición
    pub edit_bg: Hsla,
    /// Bordes y líneas guía del outline
    pub line: Hsla,
    /// Bordes de controles, kbd, chip TODO
    pub line_2: Hsla,
    pub text: Hsla,
    /// Texto secundario
    pub text_2: Hsla,
    /// Metadatos, etiquetas (≥4.5:1 sobre bg)
    pub muted: Hsla,
    /// Viñetas de bloque (decorativo)
    pub bullet: Hsla,
    /// Enlaces, #tags, [[refs]], selección, DOING/NOW
    pub accent: Hsla,
    /// accent al 13%
    pub accent_bg: Hsla,
    pub on_accent: Hsla,
    /// SOLO texto/acciones generados por IA aún no aceptados
    pub ai: Hsla,
    /// ai al 7%
    pub ai_bg: Hsla,
    /// ai al 28%
    pub ai_line: Hsla,
    pub on_ai: Hsla,
    /// Vencido / error suave
    pub warn: Hsla,
    /// MCP activo, tool call correcta
    pub ok: Hsla,
}

impl Palette {
    pub fn dark() -> Self {
        Self {
            side: rgb(0x101114).into(),
            bg: rgb(0x141518).into(),
            panel: rgb(0x17181C).into(),
            raised: rgb(0x1D1F23).into(),
            hover: rgb(0x25272C).into(),
            edit_bg: rgb(0x1B1D21).into(),
            line: rgb(0x2A2C32).into(),
            line_2: rgb(0x3A3C43).into(),
            text: rgb(0xE9E7E2).into(),
            text_2: rgb(0xBDBAB3).into(),
            muted: rgb(0x938F88).into(),
            bullet: rgb(0x6B6963).into(),
            accent: rgb(0x72C4CD).into(),
            accent_bg: rgba(0x72C4CD21).into(),
            on_accent: rgb(0x0D1A1C).into(),
            ai: rgb(0xE2B366).into(),
            ai_bg: rgba(0xE2B36612).into(),
            ai_line: rgba(0xE2B36647).into(),
            on_ai: rgb(0x1E1407).into(),
            warn: rgb(0xEF9A76).into(),
            ok: rgb(0x7CC79A).into(),
        }
    }

    pub fn light() -> Self {
        Self {
            side: rgb(0xF1EFEA).into(),
            bg: rgb(0xFBFAF7).into(),
            panel: rgb(0xF6F5F1).into(),
            raised: rgb(0xFFFFFF).into(),
            hover: rgb(0xEBE9E3).into(),
            edit_bg: rgb(0xF3F1EC).into(),
            line: rgb(0xE3E0D9).into(),
            line_2: rgb(0xCFCCC4).into(),
            text: rgb(0x1B1C1F).into(),
            text_2: rgb(0x44454A).into(),
            muted: rgb(0x67655F).into(),
            bullet: rgb(0xA3A09A).into(),
            accent: rgb(0x1C6A74).into(),
            accent_bg: rgba(0x1C6A7417).into(),
            on_accent: rgb(0xFFFFFF).into(),
            ai: rgb(0x8F5608).into(),
            ai_bg: rgba(0x8F56080D).into(),
            ai_line: rgba(0x8F560840).into(),
            on_ai: rgb(0xFFFFFF).into(),
            warn: rgb(0xB0451C).into(),
            ok: rgb(0x2F7D4F).into(),
        }
    }

    /// Every token as `(tokens.json key, colour)`, in declaration order.
    pub fn entries(&self) -> [(&'static str, Hsla); 21] {
        [
            ("side", self.side),
            ("bg", self.bg),
            ("panel", self.panel),
            ("raised", self.raised),
            ("hover", self.hover),
            ("editBg", self.edit_bg),
            ("line", self.line),
            ("line2", self.line_2),
            ("text", self.text),
            ("text2", self.text_2),
            ("muted", self.muted),
            ("bullet", self.bullet),
            ("accent", self.accent),
            ("accentBg", self.accent_bg),
            ("onAccent", self.on_accent),
            ("ai", self.ai),
            ("aiBg", self.ai_bg),
            ("aiLine", self.ai_line),
            ("onAi", self.on_ai),
            ("warn", self.warn),
            ("ok", self.ok),
        ]
    }
}
