// GENERATED by `cargo xtask tokens` from design/tokens/tokens.json. Do not edit.
use crate::fonts::{FONT_DISPLAY, FONT_MONO, FONT_UI};
use crate::ui::text_edit::FontWeight;
use crate::ui::{Pixels, SharedString, px};

/// One text style of the type scale.
#[derive(Clone, Debug, PartialEq)]
pub struct TypeStyle {
    pub family: SharedString,
    pub size: Pixels,
    pub weight: FontWeight,
    /// Line height relative to the size (1.65 = 165 %).
    pub line_height: f32,
    /// Letter spacing in em (-0.01 = -1 %).
    pub tracking_em: f32,
    pub uppercase: bool,
}

/// The design system type scale.
#[derive(Clone, Debug, PartialEq)]
pub struct TypeScale {
    /// Título de diario/página
    pub display: TypeStyle,
    pub page_title: TypeStyle,
    pub h1_block: TypeStyle,
    pub h2_block: TypeStyle,
    pub h3_block: TypeStyle,
    /// Texto de bloques
    pub body: TypeStyle,
    /// Panel derecho y agente
    pub panel_body: TypeStyle,
    pub ui: TypeStyle,
    /// Pestañas, botones
    pub ui_small: TypeStyle,
    pub caption: TypeStyle,
    /// Cabeceras de sección: FAVORITOS, RECIENTES
    pub overline: TypeStyle,
    /// Estados de tarea, fechas, kbd, tool calls
    pub mono: TypeStyle,
}

impl TypeScale {
    /// Every style as `(tokens.json key, style)`, in declaration order.
    pub fn entries(&self) -> [(&'static str, &TypeStyle); 12] {
        [
            ("display", &self.display),
            ("pageTitle", &self.page_title),
            ("h1Block", &self.h1_block),
            ("h2Block", &self.h2_block),
            ("h3Block", &self.h3_block),
            ("body", &self.body),
            ("panelBody", &self.panel_body),
            ("ui", &self.ui),
            ("uiSmall", &self.ui_small),
            ("caption", &self.caption),
            ("overline", &self.overline),
            ("mono", &self.mono),
        ]
    }
}

impl Default for TypeScale {
    fn default() -> Self {
        Self {
            display: TypeStyle {
                family: FONT_DISPLAY.into(),
                size: px(34.0),
                weight: FontWeight(600.0),
                line_height: 1.2,
                tracking_em: -0.01,
                uppercase: false,
            },
            page_title: TypeStyle {
                family: FONT_DISPLAY.into(),
                size: px(34.0),
                weight: FontWeight(600.0),
                line_height: 1.2,
                tracking_em: 0.0,
                uppercase: false,
            },
            h1_block: TypeStyle {
                family: FONT_UI.into(),
                size: px(26.0),
                weight: FontWeight(600.0),
                line_height: 1.3,
                tracking_em: 0.0,
                uppercase: false,
            },
            h2_block: TypeStyle {
                family: FONT_UI.into(),
                size: px(22.0),
                weight: FontWeight(600.0),
                line_height: 1.35,
                tracking_em: 0.0,
                uppercase: false,
            },
            h3_block: TypeStyle {
                family: FONT_UI.into(),
                size: px(18.0),
                weight: FontWeight(600.0),
                line_height: 1.4,
                tracking_em: 0.0,
                uppercase: false,
            },
            body: TypeStyle {
                family: FONT_UI.into(),
                size: px(16.0),
                weight: FontWeight(400.0),
                line_height: 1.65,
                tracking_em: 0.0,
                uppercase: false,
            },
            panel_body: TypeStyle {
                family: FONT_UI.into(),
                size: px(14.5),
                weight: FontWeight(400.0),
                line_height: 1.6,
                tracking_em: 0.0,
                uppercase: false,
            },
            ui: TypeStyle {
                family: FONT_UI.into(),
                size: px(14.0),
                weight: FontWeight(400.0),
                line_height: 1.5,
                tracking_em: 0.0,
                uppercase: false,
            },
            ui_small: TypeStyle {
                family: FONT_UI.into(),
                size: px(13.5),
                weight: FontWeight(400.0),
                line_height: 1.5,
                tracking_em: 0.0,
                uppercase: false,
            },
            caption: TypeStyle {
                family: FONT_UI.into(),
                size: px(12.5),
                weight: FontWeight(400.0),
                line_height: 1.45,
                tracking_em: 0.0,
                uppercase: false,
            },
            overline: TypeStyle {
                family: FONT_UI.into(),
                size: px(11.5),
                weight: FontWeight(600.0),
                line_height: 1.4,
                tracking_em: 0.08,
                uppercase: true,
            },
            mono: TypeStyle {
                family: FONT_MONO.into(),
                size: px(12.0),
                weight: FontWeight(500.0),
                line_height: 1.4,
                tracking_em: 0.0,
                uppercase: false,
            },
        }
    }
}

/// Layout metrics of the design system (sizes, radii, spacing).
#[derive(Clone, Debug, PartialEq)]
pub struct Metrics {
    pub titlebar: Pixels,
    pub sidebar_left: Pixels,
    pub sidebar_right: Pixels,
    pub reading_max: Pixels,
    pub tasks_max: Pixels,
    pub icon_button: Pixels,
    pub icon_button_sm: Pixels,
    pub tab_height: Pixels,
    pub tab_max: Pixels,
    pub nav_item: Pixels,
    pub bullet_gutter: Pixels,
    pub bullet: Pixels,
    pub bullet_child: Pixels,
    /// 8px margen + 18px padding tras la línea guía
    pub child_indent: Pixels,
    pub calendar_cell: Pixels,
    pub icon: Pixels,
    pub icon_sm: Pixels,
    pub icon_stroke: f32,
    pub radius_chip: Pixels,
    pub radius_control: Pixels,
    pub radius_tab: Pixels,
    pub radius_card: Pixels,
    pub radius_panel: Pixels,
    pub radius_popover: Pixels,
    pub radius_pill: Pixels,
    /// Reading column padding, top
    pub reading_pad_top: Pixels,
    /// Reading column padding, sides
    pub reading_pad_x: Pixels,
    /// Reading column padding, bottom
    pub reading_pad_bottom: Pixels,
    /// Gap between consecutive journals
    pub journal_gap: Pixels,
    /// Vertical gap between sibling blocks
    pub block_gap: Pixels,
    /// Children: margin up to the guide line
    pub child_guide_margin: Pixels,
    /// Children: padding after the guide line
    pub child_guide_pad: Pixels,
    /// Spacing scale (`space.0` to `space.11`).
    pub space: [Pixels; 12],
}

impl Default for Metrics {
    fn default() -> Self {
        Self {
            titlebar: px(52.0),
            sidebar_left: px(252.0),
            sidebar_right: px(360.0),
            reading_max: px(760.0),
            tasks_max: px(860.0),
            icon_button: px(36.0),
            icon_button_sm: px(34.0),
            tab_height: px(38.0),
            tab_max: px(190.0),
            nav_item: px(36.0),
            bullet_gutter: px(18.0),
            bullet: px(6.0),
            bullet_child: px(5.0),
            child_indent: px(26.0),
            calendar_cell: px(32.0),
            icon: px(18.0),
            icon_sm: px(15.0),
            icon_stroke: 1.7,
            radius_chip: px(5.0),
            radius_control: px(8.0),
            radius_tab: px(9.0),
            radius_card: px(10.0),
            radius_panel: px(12.0),
            radius_popover: px(14.0),
            radius_pill: px(999.0),
            reading_pad_top: px(44.0),
            reading_pad_x: px(40.0),
            reading_pad_bottom: px(80.0),
            journal_gap: px(56.0),
            block_gap: px(6.0),
            child_guide_margin: px(8.0),
            child_guide_pad: px(18.0),
            space: [
                px(0.0),
                px(2.0),
                px(4.0),
                px(6.0),
                px(8.0),
                px(10.0),
                px(12.0),
                px(16.0),
                px(20.0),
                px(24.0),
                px(40.0),
                px(56.0),
            ],
        }
    }
}
