//! Theme switching: light / dark / system, with the bundled "Bitacora Light" / "Bitacora Dark"
//! kit themes (generated from the design tokens, BIT-US-0116) and the `BitacoraTheme` global
//! (BIT-US-0115).
//!
//! The choice is kept in a GPUI global ([`ThemeController`]) and persisted to
//! `<config_dir>/settings.json` after every change.

use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime};

use rust_i18n::t;

use crate::custom_css::{self, CustomCss, Diagnostic, Overrides, Rgba8};
use crate::settings::{AppSettings, ThemePreference};
use crate::ui::menu::{PopupMenu, PopupMenuItem};
use crate::ui::theme::{BitacoraTheme, Theme, ThemeMode, ThemeRegistry};
use crate::ui::{App, Global, Hsla, Task, Window, WindowAppearance};

/// The themes shipped with the app, generated by `cargo xtask tokens`.
const BUNDLED_THEMES: &str = include_str!("../assets/themes/bitacora.json");

/// How often the open graph's `logseq/custom.css` is checked for changes.
/// Name of the bundled kit theme used in light mode.
pub const LIGHT_THEME: &str = "Bitacora Light";
/// Name of the bundled kit theme used in dark mode.
pub const DARK_THEME: &str = "Bitacora Dark";

const CSS_POLL: Duration = Duration::from_secs(2);

/// The state of the open graph's `custom.css` (BIT-T-0334).
#[derive(Default)]
struct CssState {
    path: Option<PathBuf>,
    stamp: Option<(SystemTime, u64)>,
    parsed: CustomCss,
    poller: Option<Task<()>>,
}

/// Current theme choice and where it is persisted.
pub struct ThemeController {
    settings: AppSettings,
    path: Option<PathBuf>,
    css: CssState,
}

impl std::fmt::Debug for ThemeController {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ThemeController")
            .field("settings", &self.settings)
            .field("css_path", &self.css.path)
            .finish_non_exhaustive()
    }
}

impl Global for ThemeController {}

fn mode_of(appearance: WindowAppearance) -> ThemeMode {
    ThemeMode::from(appearance)
}

/// Installs the controller and applies the saved theme. `settings_path = None`
/// disables persistence (tests).
pub fn install(cx: &mut App, settings: AppSettings, settings_path: Option<PathBuf>) {
    cx.set_global(ThemeController {
        settings,
        path: settings_path,
        css: CssState::default(),
    });
    if let Err(err) = ThemeRegistry::global_mut(cx).load_themes_from_str(BUNDLED_THEMES) {
        tracing::warn!("cannot load the bundled themes: {err}");
    }
    apply(cx, None);
}

/// Points the theme at the open graph's `logseq/custom.css` (`None` when no graph is open) and
/// starts watching it. The file is only read, never written.
pub fn set_graph_css(cx: &mut App, graph_root: Option<&Path>) {
    if cx.try_global::<ThemeController>().is_none() {
        return;
    }
    let css = &mut cx.global_mut::<ThemeController>().css;
    css.path = graph_root.map(|root| root.join("logseq").join("custom.css"));
    css.stamp = None;
    css.parsed = CustomCss::default();
    css.poller = None;
    check_css(cx);
    if graph_root.is_some() {
        let poller = cx.spawn(async move |cx| {
            loop {
                cx.background_executor().timer(CSS_POLL).await;
                cx.update(check_css);
            }
        });
        cx.global_mut::<ThemeController>().css.poller = Some(poller);
    }
    apply(cx, None);
    cx.refresh_windows();
}

/// Re-reads `custom.css` when its modification time or size changed and re-applies the theme.
/// Returns whether anything was reloaded.
pub fn check_css(cx: &mut App) -> bool {
    let Some(controller) = cx.try_global::<ThemeController>() else {
        return false;
    };
    let Some(path) = controller.css.path.clone() else {
        return false;
    };
    let stamp = std::fs::metadata(&path)
        .ok()
        .and_then(|m| Some((m.modified().ok()?, m.len())));
    if stamp == controller.css.stamp {
        return false;
    }
    let parsed = match &stamp {
        Some(_) => match std::fs::read(&path) {
            Ok(bytes) => custom_css::parse(&String::from_utf8_lossy(&bytes)),
            Err(err) => {
                tracing::warn!(path = %path.display(), "cannot read custom.css: {err}");
                CustomCss::default()
            }
        },
        None => CustomCss::default(),
    };
    let css = &mut cx.global_mut::<ThemeController>().css;
    css.stamp = stamp;
    css.parsed = parsed;
    apply(cx, None);
    cx.refresh_windows();
    true
}

/// What the open graph's `custom.css` contributed: the ignored constructs, how many values were
/// applied and the file path when it exists (for Settings > Appearance).
pub fn css_report(cx: &App) -> (Vec<Diagnostic>, usize, Option<PathBuf>) {
    cx.try_global::<ThemeController>().map_or_else(
        || (Vec::new(), 0, None),
        |c| {
            (
                c.css.parsed.diagnostics.clone(),
                c.css.parsed.applied_count(),
                c.css.path.clone().filter(|_| c.css.stamp.is_some()),
            )
        },
    )
}

/// The block bullet colour requested by `custom.css` for the current mode, if any. Kept outside
/// the GPUI `Theme` (which has no slot for it) so block rows can read it without an `App`.
pub fn bullet_color() -> Option<Hsla> {
    BULLET.lock().ok().and_then(|guard| *guard).map(hsla_of)
}

static BULLET: std::sync::Mutex<Option<Rgba8>> = std::sync::Mutex::new(None);

fn hsla_of(c: Rgba8) -> Hsla {
    crate::ui::Rgba {
        r: f32::from(c[0]) / 255.0,
        g: f32::from(c[1]) / 255.0,
        b: f32::from(c[2]) / 255.0,
        a: f32::from(c[3]) / 255.0,
    }
    .into()
}

/// Lays the `custom.css` values over the resolved theme.
fn apply_overrides(theme: &mut Theme, ov: &Overrides, font_size_free: bool) {
    let c = &mut theme.colors;
    if let Some(v) = ov.background {
        let v = hsla_of(v);
        c.background = v;
        c.popover = v;
        c.list = v;
    }
    if let Some(v) = ov.secondary_background {
        let v = hsla_of(v);
        c.sidebar = v;
        c.title_bar = v;
        c.status_bar = v;
    }
    if let Some(v) = ov.tertiary_background {
        let v = hsla_of(v);
        c.muted = v;
        c.secondary = v;
    }
    if let Some(v) = ov.text {
        let v = hsla_of(v);
        c.foreground = v;
        c.popover_foreground = v;
        c.sidebar_foreground = v;
    }
    if let Some(v) = ov.secondary_text {
        c.muted_foreground = hsla_of(v);
    }
    if let Some(v) = ov.link {
        let v = hsla_of(v);
        c.link = v;
        c.link_hover = v;
        c.link_active = v;
    }
    if let Some(v) = ov.border {
        let v = hsla_of(v);
        c.border = v;
        c.sidebar_border = v;
    }
    if let Some(v) = ov.selection {
        c.selection = hsla_of(v);
    }
    if let Some(family) = &ov.font_family {
        theme.font_family = family.clone().into();
    }
    if let (Some(px), true) = (ov.font_size, font_size_free) {
        theme.font_size = crate::ui::px(px);
    }
}

/// Sets the UI language (`None` follows the system).
pub fn set_language(cx: &mut App, window: Option<&mut Window>, language: Option<&str>) {
    update(cx, window, |s| s.language = language.map(str::to_owned));
}

/// The current settings.
pub fn settings(cx: &App) -> AppSettings {
    cx.global::<ThemeController>().settings.clone()
}

/// The current settings, `None` before [`install`] (headless tests).
pub fn try_settings(cx: &App) -> Option<AppSettings> {
    cx.try_global::<ThemeController>()
        .map(|c| c.settings.clone())
}

/// Re-applies the stored choice (call again when the OS appearance changes).
pub fn apply(cx: &mut App, window: Option<&mut Window>) {
    let settings = settings(cx);
    crate::i18n::apply(settings.language.as_deref());
    resolve_theme_names(cx);
    let mode = match settings.mode {
        ThemePreference::Light => ThemeMode::Light,
        ThemePreference::Dark => ThemeMode::Dark,
        ThemePreference::System => match &window {
            Some(window) => mode_of(window.appearance()),
            None => mode_of(cx.window_appearance()),
        },
    };
    Theme::change(mode, window, cx);
    BitacoraTheme::set_mode(mode.into(), cx);
    cx.set_reduce_motion(settings.reduce_motion);
    if let Some(size) = settings.font_size {
        let (min, max) = crate::settings::FONT_SIZE_RANGE;
        Theme::global_mut(cx).font_size = crate::ui::px(f32::from(size.clamp(min, max)));
    }
    let overrides = {
        let dark = Theme::global(cx).is_dark();
        cx.global::<ThemeController>().css.parsed.effective(dark)
    };
    if let Ok(mut bullet) = BULLET.lock() {
        *bullet = overrides.bullet;
    }
    if !overrides.is_empty() {
        let font_free = settings.font_size.is_none();
        // `Theme::update` carries the colour edits into the component tokens too.
        Theme::update(cx, |theme| apply_overrides(theme, &overrides, font_free));
    }
}

/// Points the theme's light/dark slots at the bundled Bitacora themes. 1.x settings could name
/// "Paper", a Solarized/Midnight theme or a user theme: those names no longer exist and
/// [`AppSettings::load`] drops them, so every mode resolves to the Bitacora theme.
fn resolve_theme_names(cx: &mut App) {
    let registry = ThemeRegistry::global(cx);
    let pick = |name: &str, mode: ThemeMode| match registry.themes().get(name) {
        Some(theme) if theme.mode == mode => theme.clone(),
        _ => {
            tracing::warn!(theme = %name, "bundled theme missing, using the kit default");
            match mode {
                ThemeMode::Light => registry.default_light_theme().clone(),
                ThemeMode::Dark => registry.default_dark_theme().clone(),
            }
        }
    };
    let light = pick(LIGHT_THEME, ThemeMode::Light);
    let dark = pick(DARK_THEME, ThemeMode::Dark);
    let theme = Theme::global_mut(cx);
    theme.light_theme = light;
    theme.dark_theme = dark;
}

/// Edits the settings, persists them and re-applies the theme (the settings view calls this for
/// every app-level change). Does nothing before [`install`].
pub fn edit_settings(
    cx: &mut App,
    window: Option<&mut Window>,
    edit: impl FnOnce(&mut AppSettings),
) {
    if cx.try_global::<ThemeController>().is_some() {
        update(cx, window, edit);
    }
}

fn update(cx: &mut App, window: Option<&mut Window>, edit: impl FnOnce(&mut AppSettings)) {
    let controller = cx.global_mut::<ThemeController>();
    edit(&mut controller.settings);
    if let Some(path) = &controller.path
        && let Err(err) = controller.settings.save(path)
    {
        tracing::warn!(path = %path.display(), "cannot save settings: {err}");
    }
    apply(cx, window);
    cx.refresh_windows();
}

/// Sets light / dark / system.
pub fn set_preference(cx: &mut App, window: Option<&mut Window>, pref: ThemePreference) {
    update(cx, window, |s| s.mode = pref);
}

/// Flips between light and dark (an explicit choice, leaving "System").
pub fn toggle(cx: &mut App, window: Option<&mut Window>) {
    let next = if Theme::global(cx).is_dark() {
        ThemePreference::Light
    } else {
        ThemePreference::Dark
    };
    set_preference(cx, window, next);
}

/// Fills the "Theme" dropdown with the System / Light / Dark choices.
pub fn build_menu(menu: PopupMenu, cx: &App) -> PopupMenu {
    let current = settings(cx);
    let mut menu = menu;
    for (pref, label) in [
        (ThemePreference::System, t!("theme.system")),
        (ThemePreference::Light, t!("theme.light")),
        (ThemePreference::Dark, t!("theme.dark")),
    ] {
        menu = menu.item(
            PopupMenuItem::new(label.to_string())
                .checked(current.mode == pref)
                .on_click(move |_, window, cx| set_preference(cx, Some(window), pref)),
        );
    }
    menu
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ui::testing::{TestAppContext, gpui_test};
    use crate::ui::theme::{ActiveBitacoraTheme as _, Mode, Palette, TypeStyleExt as _};

    #[gpui_test]
    fn preference_drives_theme_mode(cx: &mut TestAppContext) {
        cx.update(|cx| {
            crate::ui::init(cx);
            install(
                cx,
                AppSettings {
                    mode: ThemePreference::Dark,
                    ..AppSettings::default()
                },
                None,
            );
            assert!(Theme::global(cx).is_dark());
            assert_eq!(cx.bitacora().mode, Mode::Dark);
            assert_eq!(Theme::global(cx).theme_name().as_ref(), DARK_THEME);

            set_preference(cx, None, ThemePreference::Light);
            assert!(!Theme::global(cx).is_dark());
            assert_eq!(Theme::global(cx).theme_name().as_ref(), LIGHT_THEME);
            toggle(cx, None);
            assert!(Theme::global(cx).is_dark());
            assert_eq!(settings(cx).mode, ThemePreference::Dark);
        });
    }

    #[gpui_test]
    fn bitacora_global_follows_the_mode(cx: &mut TestAppContext) {
        cx.update(|cx| {
            crate::ui::init(cx);
            install(cx, AppSettings::default(), None);
            set_preference(cx, None, ThemePreference::Light);
            assert_eq!(cx.bitacora().mode, Mode::Light);
            assert_eq!(cx.bitacora().colors, Palette::light());
            toggle(cx, None);
            assert_eq!(cx.bitacora().mode, Mode::Dark);
            assert_eq!(cx.bitacora().colors, Palette::dark());
            // PDF export is always light.
            assert_eq!(BitacoraTheme::print().colors, Palette::light());
        });
    }

    #[gpui_test]
    fn every_type_style_and_metric_resolves(cx: &mut TestAppContext) {
        cx.update(|cx| {
            crate::ui::init(cx);
            install(cx, AppSettings::default(), None);
            let theme = cx.bitacora();
            for (name, style) in theme.type_scale.entries() {
                assert!(f32::from(style.size) >= 11.0, "{name}: size");
                assert!(style.line_height >= 1.0, "{name}: line height");
                assert!(!style.family.is_empty(), "{name}: family");
                // The style applies to an element.
                let _ = crate::ui::div().type_style(style);
            }
            assert_eq!(theme.type_scale.body.family.as_ref(), crate::fonts::FONT_UI);
            assert_eq!(
                theme.type_scale.display.family.as_ref(),
                crate::fonts::FONT_DISPLAY
            );
            assert_eq!(
                theme.type_scale.mono.family.as_ref(),
                crate::fonts::FONT_MONO
            );
            assert!(theme.type_scale.overline.uppercase);
            let m = &theme.metrics;
            assert_eq!(f32::from(m.titlebar), 52.0);
            assert_eq!(f32::from(m.sidebar_left), 252.0);
            assert_eq!(f32::from(m.reading_max), 760.0);
            assert_eq!(f32::from(m.radius_popover), 14.0);
            assert_eq!(m.space.len(), 12);
            assert!(m.icon_stroke > 1.0);
        });
    }

    #[gpui_test]
    fn kit_theme_is_generated_from_the_tokens(cx: &mut TestAppContext) {
        cx.update(|cx| {
            crate::ui::init(cx);
            install(cx, AppSettings::default(), None);
            for (pref, palette) in [
                (ThemePreference::Dark, Palette::dark()),
                (ThemePreference::Light, Palette::light()),
            ] {
                set_preference(cx, None, pref);
                let c = Theme::global(cx).colors;
                assert_eq!(c.background, palette.bg);
                assert_eq!(c.foreground, palette.text);
                assert_eq!(c.border, palette.line);
                assert_eq!(c.input, palette.line_2);
                assert_eq!(c.muted_foreground, palette.muted);
                assert_eq!(c.primary, palette.accent);
                assert_eq!(c.primary_foreground, palette.on_accent);
                assert_eq!(c.link, palette.accent);
                assert_eq!(c.sidebar, palette.side);
                assert_eq!(c.title_bar, palette.side);
                assert_eq!(c.popover, palette.raised);
                assert_eq!(c.list_hover, palette.hover);
                assert_eq!(c.danger, palette.warn);
                assert_eq!(c.success, palette.ok);
                assert_eq!(
                    Theme::global(cx).font_family.as_ref(),
                    crate::fonts::FONT_UI
                );
                assert_eq!(
                    Theme::global(cx).mono_font_family.as_ref(),
                    crate::fonts::FONT_MONO
                );
            }
        });
    }

    #[test]
    fn kit_theme_keys_exist_in_the_kit_schema() {
        use crate::ui::theme::ThemeConfig;
        let json: serde_json::Value = serde_json::from_str(BUNDLED_THEMES).expect("json");
        let themes = json["themes"].as_array().expect("themes");
        assert_eq!(themes.len(), 2, "only the two Bitacora themes are bundled");
        // A key the kit does not know is silently ignored, so compare against the kit's own
        // serialized schema.
        let known = serde_json::to_value(ThemeConfig::default()).expect("kit schema");
        let known = known["colors"].as_object().expect("colors");
        for theme in themes {
            for key in theme["colors"].as_object().expect("colors").keys() {
                assert!(known.contains_key(key), "unknown kit colour key `{key}`");
            }
        }
    }

    #[gpui_test]
    fn removed_1x_theme_names_in_settings_fall_back_to_bitacora(cx: &mut TestAppContext) {
        let tmp = tempfile::tempdir().expect("tempdir");
        let path = tmp.path().join("settings.json");
        std::fs::write(
            &path,
            r#"{"mode":"light","light_theme":"Paper","dark_theme":"Mine Dark"}"#,
        )
        .expect("write");
        cx.update(|cx| {
            crate::ui::init(cx);
            install(cx, AppSettings::load(&path), Some(path.clone()));
            assert_eq!(Theme::global(cx).theme_name().as_ref(), LIGHT_THEME);
            set_preference(cx, None, ThemePreference::Dark);
            assert_eq!(Theme::global(cx).theme_name().as_ref(), DARK_THEME);
        });
        // The obsolete keys are dropped the next time the settings are saved.
        let saved = std::fs::read_to_string(&path).expect("read");
        assert!(!saved.contains("Paper") && !saved.contains("light_theme"));
    }

    #[gpui_test]
    fn choice_is_persisted(cx: &mut TestAppContext) {
        let tmp = tempfile::tempdir().expect("tempdir");
        let path = tmp.path().join("settings.json");
        cx.update(|cx| {
            crate::ui::init(cx);
            install(cx, AppSettings::default(), Some(path.clone()));
            set_preference(cx, None, ThemePreference::Dark);
        });
        assert_eq!(AppSettings::load(&path).mode, ThemePreference::Dark);
    }

    fn rgb(c: Hsla) -> [u8; 3] {
        let rgba = crate::ui::Rgba::from(c);
        [rgba.r, rgba.g, rgba.b].map(|v| (v * 255.0).round() as u8)
    }

    #[gpui_test]
    fn reduce_motion_follows_the_setting(cx: &mut TestAppContext) {
        cx.update(|cx| {
            crate::ui::init(cx);
            install(cx, AppSettings::default(), None);
            assert!(!cx.reduce_motion());
            edit_settings(cx, None, |s| s.reduce_motion = true);
            assert!(cx.reduce_motion());
            edit_settings(cx, None, |s| s.reduce_motion = false);
            assert!(!cx.reduce_motion());
        });
        // A saved setting is applied when the app starts.
        cx.update(|cx| {
            install(
                cx,
                AppSettings {
                    reduce_motion: true,
                    ..AppSettings::default()
                },
                None,
            );
            assert!(cx.reduce_motion());
        });
    }

    fn write_css(root: &Path, css: &str) {
        std::fs::create_dir_all(root.join("logseq")).expect("mkdir");
        std::fs::write(root.join("logseq/custom.css"), css).expect("write css");
    }

    #[gpui_test]
    fn custom_css_maps_onto_the_theme_and_hot_reloads(cx: &mut TestAppContext) {
        let graph = tempfile::tempdir().expect("tempdir");
        let css = "
:root { --ls-primary-background-color: #fdf6e3; --ls-link-text-color: #ff0000;
        --ls-block-bullet-color: #00ff00; --ls-odd-thing: 1; }
.dark-theme { --ls-primary-background-color: #001122; }
body { font-family: 'Fira Sans', sans-serif; font-size: 20px; }
.weird > .selector { color: red }
";
        write_css(graph.path(), css);
        let before = std::fs::read(graph.path().join("logseq/custom.css")).expect("read");
        cx.update(|cx| {
            crate::ui::init(cx);
            install(
                cx,
                AppSettings {
                    mode: ThemePreference::Light,
                    ..AppSettings::default()
                },
                None,
            );
            set_graph_css(cx, Some(graph.path()));
            let theme = Theme::global(cx);
            assert_eq!(rgb(theme.colors.background), [0xfd, 0xf6, 0xe3]);
            assert_eq!(rgb(theme.colors.link), [0xff, 0, 0]);
            assert_eq!(theme.font_family.as_ref(), "Fira Sans");
            assert_eq!(f32::from(theme.font_size), 20.0);
            assert_eq!(bullet_color().map(rgb), Some([0, 0xff, 0]));
            let (diagnostics, applied, path) = css_report(cx);
            assert!(applied >= 5 && path.is_some());
            assert!(
                diagnostics
                    .iter()
                    .any(|d| d.subject.contains("--ls-odd-thing"))
            );
            assert!(diagnostics.iter().any(|d| d.subject.contains(".weird")));

            // Dark mode picks the `.dark-theme` override.
            set_preference(cx, None, ThemePreference::Dark);
            assert_eq!(rgb(Theme::global(cx).colors.background), [0, 0x11, 0x22]);

            // The font size set in Settings wins over the stylesheet.
            edit_settings(cx, None, |s| s.font_size = Some(14));
            assert_eq!(f32::from(Theme::global(cx).font_size), 14.0);

            // Editing the file is picked up by the poller.
            write_css(
                graph.path(),
                ":root { --ls-primary-background-color: #123456; } /* changed */",
            );
            assert!(check_css(cx));
            assert!(!check_css(cx), "unchanged file is not re-read");
            set_preference(cx, None, ThemePreference::Light);
            assert_eq!(rgb(Theme::global(cx).colors.background), [0x12, 0x34, 0x56]);
            assert_eq!(bullet_color(), None);

            // Closing the graph drops the overrides.
            set_graph_css(cx, None);
            assert_ne!(rgb(Theme::global(cx).colors.background), [0x12, 0x34, 0x56]);
        });
        // The stylesheet is only ever read by the app.
        assert!(before.starts_with(b"\n:root"));
    }
}
