//! `cargo xtask tokens`: generate the app colour palette from the vendored design tokens
//! (`design/tokens/tokens.json`, ADR-032) and check WCAG contrast.
//!
//! - `tokens`: write `crates/bitacora-app/src/ui/theme/palette.rs`.
//! - `tokens --check`: fail when the generated file is stale (CI).
//! - `tokens --contrast`: fail when a text token drops below 4.5:1 on a surface.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow, bail};
use serde_json::{Map, Value};

const TOKENS: &str = "design/tokens/tokens.json";
const PALETTE: &str = "crates/bitacora-app/src/ui/theme/palette.rs";

const TEXT: [&str; 6] = ["text", "text2", "muted", "accent", "ai", "warn"];
const SURFACES: [&str; 5] = ["bg", "side", "panel", "raised", "hover"];
const PAIRS: [(&str, &str); 2] = [("onAccent", "accent"), ("onAi", "ai")];

pub fn run(args: &[String]) -> Result<bool> {
    let root = repo_root()?;
    let tokens = read_tokens(&root.join(TOKENS))?;
    match args.first().map(String::as_str) {
        None => {
            let target = root.join(PALETTE);
            std::fs::write(&target, generate(&tokens)?)
                .with_context(|| format!("writing {}", target.display()))?;
            println!("wrote {PALETTE}");
            Ok(true)
        }
        Some("--check") => {
            let want = generate(&tokens)?;
            let have = std::fs::read_to_string(root.join(PALETTE)).unwrap_or_default();
            if have == want {
                println!("{PALETTE} is up to date");
                Ok(true)
            } else {
                eprintln!("{PALETTE} is stale: run `cargo xtask tokens` and commit the result");
                Ok(false)
            }
        }
        Some("--contrast") => contrast(&tokens),
        Some(other) => bail!("unknown `tokens` option `{other}` (use --check or --contrast)"),
    }
}

fn repo_root() -> Result<PathBuf> {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(Path::to_path_buf)
        .ok_or_else(|| anyhow!("xtask manifest has no parent directory"))
}

fn read_tokens(path: &Path) -> Result<Value> {
    let text =
        std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    serde_json::from_str(&text).with_context(|| format!("parsing {}", path.display()))
}

fn modes(tokens: &Value) -> Result<&Map<String, Value>> {
    tokens
        .get("color")
        .and_then(Value::as_object)
        .ok_or_else(|| anyhow!("tokens.json has no `color` object"))
}

fn mode<'a>(colors: &'a Map<String, Value>, name: &str) -> Result<&'a Map<String, Value>> {
    colors
        .get(name)
        .and_then(Value::as_object)
        .ok_or_else(|| anyhow!("tokens.json has no `color.{name}`"))
}

fn value_of(group: &Map<String, Value>, name: &str) -> Result<String> {
    let hex = group
        .get(name)
        .and_then(|t| t.get("$value"))
        .and_then(Value::as_str)
        .ok_or_else(|| anyhow!("token `{name}` has no string $value"))?
        .trim_start_matches('#')
        .to_ascii_uppercase();
    if (hex.len() == 6 || hex.len() == 8) && hex.chars().all(|c| c.is_ascii_hexdigit()) {
        Ok(hex)
    } else {
        bail!("token `{name}` is not #RRGGBB or #RRGGBBAA: {hex}")
    }
}

/// `editBg` -> `edit_bg`, `text2` -> `text_2`, `line2` -> `line_2`.
fn snake(name: &str) -> String {
    let mut out = String::new();
    for (i, c) in name.chars().enumerate() {
        if i > 0 && (c.is_ascii_uppercase() || c.is_ascii_digit()) {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
    }
    out
}

fn generate(tokens: &Value) -> Result<String> {
    let colors = modes(tokens)?;
    let dark = mode(colors, "dark")?;
    let light = mode(colors, "light")?;
    let names: Vec<&String> = dark.keys().collect();
    if !light.keys().eq(dark.keys()) {
        bail!("`color.dark` and `color.light` must define the same tokens in the same order");
    }

    let mut rs = String::new();
    rs.push_str(
        "// GENERATED by `cargo xtask tokens` from design/tokens/tokens.json. Do not edit.\n",
    );
    rs.push_str("use crate::ui::{Hsla, rgb, rgba};\n\n");
    rs.push_str("/// Semantic Bitacora colours (design system tokens).\n");
    rs.push_str("#[derive(Clone, Copy, Debug, PartialEq)]\npub struct Palette {\n");
    for n in &names {
        if let Some(d) = dark[*n].get("$description").and_then(Value::as_str) {
            writeln!(rs, "    /// {d}")?;
        }
        writeln!(rs, "    pub {}: Hsla,", snake(n))?;
    }
    rs.push_str("}\n\nimpl Palette {\n");
    for (fname, group) in [("dark", dark), ("light", light)] {
        writeln!(rs, "    pub fn {fname}() -> Self {{\n        Self {{")?;
        for n in &names {
            let hex = value_of(group, n)?;
            let ctor = if hex.len() == 6 { "rgb" } else { "rgba" };
            writeln!(rs, "            {}: {ctor}(0x{hex}).into(),", snake(n))?;
        }
        rs.push_str("        }\n    }\n\n");
    }
    writeln!(
        rs,
        "    /// Every token as `(tokens.json key, colour)`, in declaration order.\n    pub fn entries(&self) -> [(&'static str, Hsla); {}] {{\n        [",
        names.len()
    )?;
    for n in &names {
        writeln!(rs, "            (\"{n}\", self.{}),", snake(n))?;
    }
    rs.push_str("        ]\n    }\n}\n");
    Ok(rs)
}

fn luminance(hex: &str) -> f64 {
    let channel = |i: usize| {
        let v = f64::from(u8::from_str_radix(&hex[i..i + 2], 16).unwrap_or(0)) / 255.0;
        if v <= 0.03928 {
            v / 12.92
        } else {
            ((v + 0.055) / 1.055).powf(2.4)
        }
    };
    0.2126 * channel(0) + 0.7152 * channel(2) + 0.0722 * channel(4)
}

fn ratio(a: &str, b: &str) -> f64 {
    let (la, lb) = (luminance(a), luminance(b));
    (la.max(lb) + 0.05) / (la.min(lb) + 0.05)
}

fn contrast(tokens: &Value) -> Result<bool> {
    let mut ok = true;
    for (mode_name, group) in modes(tokens)? {
        let group = group
            .as_object()
            .ok_or_else(|| anyhow!("`color.{mode_name}` is not an object"))?;
        let mut checks: Vec<(&str, &str)> = Vec::new();
        for fg in TEXT {
            for bg in SURFACES {
                checks.push((fg, bg));
            }
        }
        checks.extend(PAIRS);
        for (fg, bg) in checks {
            let r = ratio(&value_of(group, fg)?, &value_of(group, bg)?);
            let pass = r >= 4.5;
            ok &= pass;
            println!(
                "{} {mode_name:5} {fg:9} on {bg:7} {r:5.1}:1",
                if pass { "OK " } else { "LOW" }
            );
        }
    }
    Ok(ok)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn snake_case_matches_upstream_generator() {
        assert_eq!(snake("editBg"), "edit_bg");
        assert_eq!(snake("text2"), "text_2");
        assert_eq!(snake("onAccent"), "on_accent");
    }

    #[test]
    fn vendored_tokens_pass_contrast() {
        let root = repo_root().expect("root");
        let tokens = read_tokens(&root.join(TOKENS)).expect("tokens");
        assert!(contrast(&tokens).expect("contrast"));
    }
}
